- .travis.yml
- spec/board_spec.rb
- spec/card_spec.rb
> Test against Ruby 2.1 and fix spec failures

- lib/trello/card.rb
- spec/card_spec.rb
As per issue #105 just added the new label colours that trello supports. 
Did not have to change spec for this....
> New label colours

- lib/trello/board.rb
- spec/board_spec.rb
- spec/spec_helper.rb
> Add starred field to board

- lib/trello/board.rb
Hi guys,
I wanted to edit the `permissionLevel` of a board I just created, and found in the Trello API Reference that it's possible. Here is a PR to add this functionality to the gem.
Let me know if there is something I should be doing better.
Thanks.
> Board update prefs

- lib/trello/board.rb
- spec/board_spec.rb
> Add & Remove a member from a board

- README.md
This should save some ppl from having to search the internet for the solution.
> Update the README configuration with the scope GET parameter

- lib/trello/organization.rb
Adds ability to retrieve memberships data from organization. This PR fixes #150.
> Add memberships attribute to organization

- lib/trello/card.rb
- lib/trello/checklist.rb
- spec/checklist_spec.rb
Same as:
https://github.com/jeremytregunna/ruby-trello/pull/158
plus adding tests.
> Allow to create a checklist with a card_id

- lib/trello/label.rb
Currently there is no way to set a label to no color.
> Need to allow no color labels

- lib/trello/card.rb
- spec/card_spec.rb
Fixes #172 
I didn't spend much effort on the spec since it's labeled to be refactored.  
If you could merge this soon, it would be very helpful as we are blocking on this problem.
> Fixes Card#save's usage of idLabels

- lib/trello.rb
- lib/trello/card.rb
- lib/trello/comment.rb
Adds a **comment** model, which has the attributes:
- :action_id
- :text
- :date
- :member_creator_id
And the methods:
- Card
- List
- Board
- Delete
Also adds a "comments" method in the card model
> Comment model

- lib/trello/list.rb
- spec/list_spec.rb
https://developers.trello.com/advanced-reference/list#post-1-lists-idlist-archiveallcards
> Adds ability to archive all the cards of a list

- lib/trello/list.rb
- spec/list_spec.rb
More info in Trello's API docs: https://developers.trello.com/advanced-reference/list#post-1-lists.
> Adds support for idListSource (source_list_id) to List

- lib/trello/board.rb
- lib/trello/card.rb
- lib/trello/checklist.rb
- lib/trello/label.rb
- lib/trello/list.rb
- lib/trello/webhook.rb
- spec/array_spec.rb
- spec/board_spec.rb
- spec/card_spec.rb
- spec/checklist_spec.rb
- spec/label_spec.rb
- spec/list_spec.rb
- spec/spec_helper.rb
- spec/webhook_spec.rb
```ruby
@client_bob = Trello::Client.new(
:consumer_key => YOUR_CONSUMER_KEY,
:consumer_secret => YOUR_CONSUMER_SECRET,
:oauth_token => "Bob's access token",
:oauth_token_secret => "Bob's access secret"
)
@client_bob.create(:card, name: 'Awesome card', list_id: LIST_ID)
```
Above code fails. This pr fixes it.
> Fix creating resources from client

- lib/trello/action.rb
- lib/trello/attachment.rb
- lib/trello/card.rb
- lib/trello/checklist.rb
- lib/trello/comment.rb
- lib/trello/item.rb
- lib/trello/item_state.rb
- lib/trello/label.rb
- lib/trello/label_name.rb
- lib/trello/list.rb
- lib/trello/member.rb
- lib/trello/notification.rb
- lib/trello/organization.rb
- lib/trello/plugin_datum.rb
- lib/trello/token.rb
- lib/trello/webhook.rb
- spec/action_spec.rb
- spec/card_spec.rb
- spec/checklist_spec.rb
- spec/item_spec.rb
- spec/label_spec.rb
- spec/list_spec.rb
- spec/member_spec.rb
- spec/notification_spec.rb
- spec/organization_spec.rb
- spec/token_spec.rb
- spec/webhook_spec.rb
`#update_fields` overrides attributes with `nil`s. This pr fixes it.
> Fix #update_fields

- lib/trello/board.rb
- spec/board_spec.rb
Hi there,
This adds the option to get all the checklists from a given board. Simple stuff, really.
Please let me know if we need any further adjustments.
Cheers,
G.V.
> Adding checklists to board

- lib/trello/attachment.rb
Added position "pos" attribute for attachments (new in Trello)
> Position attribute for attachments

- lib/trello/board.rb
There is a possibility missing in the comment, to add options :admins
> admins as filter through members

- .gitignore
- Gemfile
- lib/trello/association_proxy.rb
- spec/cassettes/get_lists.yml
- spec/integration/board_lists_spec.rb
- spec/spec_helper.rb
Fix the `AssociationProxy#to_a` issue which mentioned in https://github.com/jeremytregunna/ruby-trello/issues/274
> Fix AssociationProxy#to_a and #to_ary

- .github/pull_request_template.md
- CHANGELOG.md
- README.md
- ruby-trello.gemspec
- Bump to 2.2.1
- Create changelog
- Update README
- Use GitHub issue instead of Trello board for the bug report
- Create a PR template
> Bump 2.2.1

- CHANGELOG.md
- Gemfile
- ruby-trello.gemspec
- spec/spec_helper.rb
A securify fix for [CVE-2020-10663](https://www.ruby-lang.org/en/news/2020/03/19/json-dos-cve-2020-10663/)
> Fix CVE-2020-10663

- CHANGELOG.md
- lib/trello/board.rb
- spec/board_spec.rb
- spec/cassettes/can_success_update_bong_a_board.yml
- spec/integration/board/update!_spec.rb
Fix #288 
`Trello::Board#update!` using the wrong key to update description.
> Fix "Trello::Board#update! fail to update description"

- .travis.yml
- Makefile
- README.md
- docker-compose.yml
* Support Ruby 3
* Add Ruby 3 and ActiveModel 6.1 to TravisCI config
> Support ruby 3
