jeremytregunna/ruby-trello

.gitignore
There's no need to include these in the git repo as people can (and should) generate them themselves using the `yardoc` command.
=> gitignoring /doc and /.yardoc

README.md
* Without showing full URL, I thought I had to switch out `1` for my board
number or something
=> Show full URL for step 2 of basic authorization

lib/trello/label_name.rb, spec/board_spec.rb
Fixing more of issue #113 
this will fix the `board#labels` method and anything else that uses the `label_name` class.
=> Add new labels to board

lib/trello/board.rb, lib/trello/card.rb, lib/trello/label.rb, spec/board_spec.rb, spec/card_spec.rb, spec/label_spec.rb, spec/spec_helper.rb
The number of labels attached to a board or card is no longer fixed. The
trello web api supports a few new calls to read, set and update those
labels. This commit reflects these changes in the classes:
- `Trello::Label`
- `Trello::Card`
- `Trello::Board`
The changes are suposed to be backward compatible.
=> Implements new trello label api

ruby-trello.gemspec, spec/board_spec.rb
From https://github.com/rubysec/ruby-advisory-db:
Name: rest-client
Version: 1.7.3
Advisory: CVE-2015-1820
Criticality: Unknown
URL: https://github.com/rest-client/rest-client/issues/369
Title: rubygem-rest-client: session fixation vulnerability via
Set-Cookie headers in 30x redirection responses
Solution: upgrade to >= 1.8.0
Also fix test suite.
=> Upgrade rest-client to ~> 1.8.0

ruby-trello.gemspec, spec/board_spec.rb
Version bump on rest-client to 1.8.x fixes a [vulnerability](https://isitvulnerable.com/vulns/557513c4-f150-429c-b7f2-58e21936a535). This PR updates the gemspec to avoid the vulnerability.
Also, a failing test was fixed so the entire suite now passes.
I cloned the repo and ran all the rspec tests. They pass.
=> Updates rest-client version

lib/trello/list.rb, spec/list_spec.rb
**What**: Add `move_all_cards` method to lists. 
**Why**: My CI process automatically moves cards from a 'Merged but Undeployed' list to a 'Deployed to Staging - Today's/Date' list, but it currently does it one card at a time. There are potentially 10+ cards in that list, and it's way faster to batch them.
=> Add move_all_cards to list.rb

lib/trello/list.rb, spec/list_spec.rb
*What*: adding `pos` to list create/update payload
*Why*: so that I can create a list before or after another list, and avoid reordering my lists every time my CI script creates a new 'Deployed This/Week' list
=> Allow list position to be set and updated

lib/trello/checklist.rb, lib/trello/item.rb, spec/checklist_spec.rb, spec/item_spec.rb, spec/spec_helper.rb
I needed a way to create a lot of cards each having a checklist made of the same items.  This pull request makes it possible to take a checklist object and make a copy of it with the same name, board id, and set of items.  The new copy is a different object in Trello and can be given to a card.
The code I used this in looked something like ...
```ruby
list_id = "12345abcde12345"
existing_checklist = Trello::Checklist.find "abcde12345abcde"
new_cards_details = [
{ name: "My First Card", description: "This is information about my first card." },
{ name: "A Second Card", description: "My second card can be described as such." }
]
new_cards_details.each do |card_details|
new_card = Trello::Card.create card_details.merge(list_id: list_id)
new_card.add_checklist existing_checklist.copy
end
``` …
=> Copy a checklist

lib/trello/organization.rb
This PR maps the following new attributes for the organization object:
- invited
- website
- logo_hash
- billable_member_count
- active_billable_member_count
It also fixes the the mapping of **description** to the new name **desc** in the API response.
=> Add new attributes to organization

ruby-trello.gemspec
Since we dropped support for EOL 1.9.3
=> Bump minimum version of Ruby to 2.0

lib/trello/board.rb, lib/trello/card.rb, spec/board_spec.rb
The Trello API returns 50 board labels max by default:
https://developers.trello.com/advanced-reference/board#get-1-boards-board-id-labels
There is currently no recognition of this in the ruby-trello and it looks like you are getting all the labels.  This can be quite dangerous to script against because you potentially won't see all the labels that exist.
I am not sure of the best way to make this change.  Suggestions welcome.  But I think the most important part is that the default limit isn't left at 50 without an indication to the caller that they aren't getting all the labels.
=> Pass default label limit of the max 1000

spec/board_spec.rb, spec/card_spec.rb
This PR should address existing rspec warnings related to the new expect syntax and error assertions. Follow up to #140.
=> Address rspec warnings

Gemfile, README.md, lib/trello.rb, spec/spec_helper.rb, spec/trello_spec.rb
This PR is intended to make it easier for new users of this gem to get up and running with basic authorization. The existing README instructions are now codified, allowing developers to issue a few commands on console to grab the public key and member token:
```ruby
irb> require 'trello'
irb> Trello.open_public_key_url                         # copy your public key
irb> Trello.open_authorization_url key: 'yourpublickey' # copy your member token
```
I've done something similar for [my Trello client gem](https://github.com/rossta/tacokit.rb#authentication) and thought it would be useful here as well.
=> Authorization convenience methods

lib/trello/checklist.rb, spec/checklist_spec.rb
Addresses #159 to remove the redundant data from the checklist post API.
=> Removes board_id from checklist creation

lib/trello/card.rb, spec/card_spec.rb
Includes params for including or excluding associated card properties, such as due dates, checklists, and members. The default behavior is to copy everything as per [Trello API docs](https://developers.trello.com/advanced-reference/card#post-1-cards). Note that the duplication takes place via an API call and not locally as class instances, so the source card should be saved to Trello before copying to assure that it's current data will be used when duplicated.
Copy the source card with all attributes and return the duplicated card:
`Card.create(list_id: list.id, source_card_id: source_card.id)` 
Copy the source card with assigned members and checklists only (no due date) and return the duplicated card:
`Card.create(list_id: list.id, source_card_id: source_card.id, source_card_properties: …
=> Adds card copying.

lib/trello.rb, spec/trello_spec.rb
`:scope` is a documented option of `Trello.authorize_url`, but it is ignored and replaced with the default "read,write,account". This change uses the scope provided in the options, but defaults to "read,write,account".
=> Allow scope to be passed to Trello.authorize_url

lib/trello/card.rb
When creating cards with labels, the labels were not being assigned. This was because the name of attribute being posted was wrong. As it can be seen in [Trello's Documentation](https://developers.trello.com/advanced-reference/card#post-1-cards) the parameter name is idLabels instead of labels
=> Fixes card creation with labels

lib/trello/card.rb
I have a Rails app with an html form, this form has a file input wich uploads the file and Rails handles it to me as an instance of  `ActionDispatch::Http::UploadedFile`.
This object has the necessary methods for the [rest-client gem](https://github.com/rest-client/rest-client/blob/30ef4d39cac74ecffc8cd171f69dc1537ea0aef1/lib/restclient/payload.rb#L41) (the gem that ruby-trello uses to execute the requests) to detect and handle it as a file, so I should be able to pass it directly to `Trello::Card#add_attachment`, without converting it to an instance of `File` first.
Unfortunately, `Trello::Card#add_attachment` instead of checking if the received object responds to the methods that will be called (in this case they're actually called in the [rest-client …
=> Avoid type checking when adding attachments to a card

lib/trello/net.rb, spec/client_spec.rb
https://github.com/jeremytregunna/ruby-trello/issues/193
This modifies the exception handling behavior in `TInternet` class
method `try_execute`. `RestClient::Exceptions` which don't bear an HTTP
response code (i.e. in the case of a connection timeout) will be raised
instead of wrapped in a `Response` struct and returned.
=> Bubble up non-response RestClient::Exceptions

ruby-trello.gemspec
Updating oauth gem requirement to allow `0.4.5` or greater (current as of this PR is `0.5.1`)
* Needed this because another gem had updated their gem requirements to use `oauth ~> 0.5.0`
* CLA Signed
=> Updating gemspec: oauth >= 0.4.5

lib/trello/checklist.rb, lib/trello/item.rb, spec/checklist_spec.rb, spec/spec_helper.rb
Adding `idCard` to the test data caused other tests to fail around
`Checklist#copy`. It looked to me like it was missing the `cardId`
parameter in the implementation, so I added it there to fix the specs.
=> Add checklist method to update item state

lib/trello/card.rb, spec/card_spec.rb
See #202 for more details. This PR adds support for adding/removing votes to a card. It also adds idMembersVoted to card attributes (though this last part is WIP)
Authenticate and execute the following code:
```ruby
card = Trello::Card.find('id-of-card')
card.upvote
card.remove_upvote
card.upvote
card.upvote
card.upvote
card.remove_upvote
card.remove_upvote
```
I'll be able to add `idMembersVoted` to the PR tomorrow (2016-08-04)
=> Allow authenticated user to vote/remove vote on card, add idMembersVoted to card

lib/trello/card.rb, ruby-trello.gemspec, spec/card_spec.rb
Hi
Since I needed the card creation time. Instead of a dirty override to add the method and maybe some other pepole need this method I added it. Even if it's not in the JSON you can find it in the ID.
(http://help.trello.com/article/759-getting-the-time-a-card-or-board-was-created) 
I only added it on the Card object this method should work with the Board object.
=> Adding a created_at method

ruby-trello.gemspec
used rest-client 1.8.0 till now which misses some features of 2.0.0 but
seems to be compatible with with ruby-trello. Using ``>=`` will enable usage of 2.0.0 but won't block the gem for users of rest-client 1.8.0
Jruby builds fail as they do on current master, rest should be fine
=> enable use of newer rest-client version

lib/trello/card.rb, ruby-trello.gemspec, spec/card_spec.rb
dueComplete is an optional flag on [PUT /1/cards/[card id or shortlink]](https://developers.trello.com/advanced-reference/card#put-1-cards-card-id-or-shortlink) which checks off the due date
=> added dueComplete flag and associated test

lib/trello/board.rb
Hello!
the gem is awesome, thanks for publish it!
With this simple change, you get de plugin_data for the boards. It gives us usefull information about the name of the custom fields.
https://developers.trello.com/advanced-reference/board#get-1-boards-board-id-pluginData
=> Adding plugin_data to board

README.md
The old URL loads a non-existant trello board.
=> Trello API documentation URL  has changed.

lib/trello/card.rb, spec/card_spec.rb
Adds an ``move_to_list_on_any_board`` instance method to
``Trello::Card`` which may move the card to the specified list on any
board. It uses either ``move_to_list`` or ``move_to_board`` as the API
does not move the card if you use the wrong call, e.g. it does not
move the card when using ``move_to_board`` with the target list and
the card being on the same board and ``move_to_list`` does not move the
card if the list is on another board.
=> add Card#move_to_list_on_any_board 

lib/trello.rb, lib/trello/client.rb, lib/trello/error.rb, ruby-trello.gemspec, spec/client_spec.rb
Differentiating between `4xx` and `5xx` errors is difficult because Trello doesn't return structured error information. Also `429` (rate limit exceeded) should be handled differently to other `4xx` errors. 
This PR adds the HTTP status code to the `Trello::Error` class as `#status_code` to allow more reliable error handling.
=> Error status code

lib/trello/label.rb
Labels created on Trello don't seem to set anything for `uses`, thus it's always nil and labels will never pass the `Label#valid?` check, meaning that you can't remove labels from cards using the `ruby-trello` gem. 
Apologies, but I haven't done anything with the tests as there were 23 failures from a clean fork and I'm not here to fix those!
=> Remove the required presence of 'uses' field

lib/trello.rb, lib/trello/board.rb, lib/trello/card.rb, lib/trello/custom_field.rb, lib/trello/custom_field_item.rb, lib/trello/custom_field_option.rb, spec/board_spec.rb, spec/card_spec.rb, spec/custom_field_item_spec.rb, spec/custom_field_option_spec.rb, spec/custom_field_spec.rb, spec/spec_helper.rb
A few months ago, Trello moved the Custom Fields Power-Up from `pluginData` to make it a core component of the Trello API ([Trello Docs](https://developers.trello.com/v1.0/docs/getting-started-custom-fields)). So the way the gem is written now you can no longer access data in the Custom Fields power-up.
I tried to organize it as intuitively as possible, but the API organizes things very strangely if you look through the links below and try to make sense of it. I can explain things if it doesn't make sense why I wrote it the way I did, or add more documentation if necessary.
Custom Field documentation: https://developers.trello.com/v1.0/reference#custom-fields
Custom Field Item documentation: https://developers.trello.com/v1.0/reference#setting-custom-field-values-on-cards
=> Adds custom fields

lib/trello/basic_data.rb, spec/basic_data_spec.rb
Hi,
I noticed that grouping cards by list didn't work properly, so I implemented the hash equality in `BasicData`.
While doing that, I noticed a small bug in the current implementation of `BasicData#==`: it didn't check for the concrete type of BasicData object, which allowed for a situation where a card could be identified as being equal to a list (or any other subclass of `BasicData`).
=> Improve equality of BasicData objects

.travis.yml
Bundler >= 2.0 requires Ruby version >= 2.3.0. 
As of January 3, 2019, Bundler >= 2.0 is the default version installed by RubyGems. 
This causes the majority of builds for `ruby-trello` to break on Travis. 
While Ruby versions <= 2.3.0 are supported by `ruby-trello`, the builds should continue to work. 
Use the [pessimistic version constraint](https://guides.rubygems.org/patterns/#pessimistic-version-constraint) to install the latest version of bundler in the 1.x series on Travis.
=> Install latest version of bundler in the 1.x series on Travis

lib/trello/card.rb, spec/card_spec.rb
- Presently, when calling `Card#members`, the method queries the `/1/members` API endpoint.
- According to [the Trello API documentation](https://developers.trello.com/docs/rate-limits#section-special-route-limits), this endpoint has much stricter rate limits.
- Trello recommend that member lookups should be scoped to the resource they relate to, like `/1/cards/:id/members` and `/1/boards/:id/members`.
- Change the behaviour of `Card#members` to scope the query to the card.
- The scoped endpoint [is documented](https://developers.trello.com/reference/#cardsidmembers).
- This change reduces the likelihood of hitting Trello rate limits when looking up members on boards with lots of cards.
=> Scope lookup of card members to the card resource

lib/trello/basic_data.rb, lib/trello/board.rb, lib/trello/card.rb, lib/trello/custom_field.rb, lib/trello/custom_field_item.rb, lib/trello/label.rb, lib/trello/member.rb
I have done a fix to compatible with Active Model 5.2.
- Change`@attributes` to `@__attributes`
- Prevent Dirty to use `ActiveModel::AttributeMutationTracker`.
- Ref: [dirty source code](https://github.com/rails/rails/blob/v5.2.3/activemodel/lib/active_model/dirty.rb#L264-L268)
- Add `changes_applied` method for save
- [Rails 5 Dirty doc](https://github.com/rails/rails/blob/v5.2.3/activemodel/lib/active_model/dirty.rb#L45-L49)
- [Rails 4 Dirty doc](https://github.com/rails/rails/blob/v4.0.7/activemodel/lib/active_model/dirty.rb#L41-L44)
=> Compatible with Active Model 5.2

.travis.yml
From [the TravisCI docs][1]:
> Language-specific workers have multiple runtimes for their respective
> language (for example, Ruby workers have about 10 Ruby
> versions/implementations).
Setting the `language` key should speed up and stabilize builds for Ruby
versions that are already installed on TravisCI.
[1]: https://docs.travis-ci.com/user/reference/precise/#runtimes
=> Add language key to .travis.yml

ruby-trello.gemspec
It's deprecated and may be removed down the line.
https://www.rubydoc.info/github/rubygems/rubygems/Gem%2FSpecification:rubyforge_project
=> remove rubyforge_project from gemspec

lib/trello/action.rb, spec/action_spec.rb
The member_creator on Action call the master member endpoint. The member
endpoint has a strong rate limit so need to be avoid in flavor of the
nested one. Same result are in the nested one.
=> Replace member_creator in Action by nested one

.travis.yml, Gemfile, README.md, lib/trello/board.rb, lib/trello/card.rb, lib/trello/custom_field.rb, lib/trello/custom_field_item.rb, lib/trello/label.rb, lib/trello/member.rb, spec/card_spec.rb, spec/custom_field_item_spec.rb, spec/custom_field_spec.rb, spec/label_spec.rb, spec/spec_helper.rb
The `#update_fields` issue which mentioned in https://github.com/jeremytregunna/ruby-trello/issues/272 happens in four models - Card, CustomFieldItem, CustomField, Label. 
I have done a fix for these four models. The fix may not be very DRY. But I think it's easy enough for reading and clearly enough to show what I have done.
1. Extract the old `#update_fields` method to a new `#initialize_fields` method in each problem model.
2. Refactor `#update_fields` to do two things
1. Mark those **changed** **updateable** fields by call `"#{fieldName}_will_change!"`
2. Call `#initialize_fields`
3. Override `#initialze` to call `#initialize_fields` instead of `#update_fields`
When I do some research on it, I find the `Card#update_fields` contains too much responsibility. And all these API models …
=> Fix #update_field issue

CHANGELOG.md, README.md, ruby-trello.gemspec
Release ruby-trello 3.0.0
* [Fix "Trello::Board#update! fail to update description"](https://github.com/jeremytregunna/ruby-trello/pull/289)
* [Add `Trello::List#move_to_board`](https://github.com/jeremytregunna/ruby-trello/pull/297)
* Use schema to handle attribute register work
* Standardize all data models' initialize/save/update!/update_fields process.
* [Breaking] some data model's attribute names changes, check each data model for details
* Support Ruby 3 (ActiveModel >= 6)
=> Release 3.0.0

Makefile, lib/trello/comment.rb, spec/cassettes/can_get_comments_board.yml, spec/cassettes/can_get_comments_card.yml, spec/cassettes/can_get_comments_list.yml, spec/cassettes/comment_delete.yml, spec/cassettes/comment_find_with_id.yml, spec/integration/comment/association/board_spec.rb, spec/integration/comment/association/card_spec.rb, spec/integration/comment/association/list_spec.rb, spec/integration/comment/delete_spec.rb, spec/integration/comment/find_spec.rb
Fix the bug in #301 by changing `action_id` to `id` in `Trello::Comment`
=> Comment action

.github/workflows/main.yml
Zero terminated float values in GitHub Actions CI configurations are truncated, leading to unexpected behavior.  In this instance this results loading an unexpected Ruby or ActiveModel version for several CI matrix entries.
Specifically, the unquoted '3.0' is interpreted as '3', and the latest Ruby 3 version - at this time of writing 3.1.1 - is loaded.  To ensure that a 3.0.x version is loaded, we need to add quotes.
In the ActiveModel case, use of an unquoted '6.0' is interpreted as '6' and ActiveModel 6.1.4.6 is loaded at this time.  To ensure a 6.0.x version is loaded, we need to add quotes.
The unquoted '7.0' would have similar problems if and when a Rails 7.1.x is released..
Look at the Actions tab for the CI runs and examine the setup Ruby step in detail for recent runs.  Once this …
=> Fix truncation issue in CI configuration entries

Gemfile, README.md, lib/trello.rb, ruby-trello.gemspec, spec/spec_helper.rb
This is a followup to https://github.com/jeremytregunna/ruby-trello/pull/307. This removes the gemspec dependency on rest-client to allow apps the option to remove their dependency on rest-client in favor of faraday (or other http clients in the future).
rest-client is out of date and does not appear to be actively maintained. This allows apps to remove the outdated gem from their dependency trees.
The changes here are all configuration, so perhaps the best place to start is by running the tests.
Include ruby-trello in a rails app and test it configured to use each of rest-client and faraday.
=> Remove rest-client dependency in the gemspec and default to faraday

.github/workflows/main.yml, CHANGELOG.md, Gemfile, README.md, matrixeval.yml, ruby-trello.gemspec, spec/spec_helper.rb
Because [oauth-ruby drop support for Ruby < 2.7 and Rails < 6](https://github.com/oauth-xx/oauth-ruby/blob/migrated/CHANGELOG.md). So we have to:
- Drop support for Ruby 2.5, 2.6
- Drop support for jRuby (May consider add it back, after jRuby upgrade to 2.7)
- Drop support for Rails 4 and 5
=> Drop support for Ruby < 2.7 and Rails < 6

lib/trello/card.rb, lib/trello/net.rb, lib/trello/net/faraday.rb, lib/trello/net/rest_client.rb, ruby-trello.gemspec, spec/card_spec.rb, spec/cassettes/can_add_a_file_on_a_card_with_farady.yml, spec/integration/card/add_and_remove_attachment_spec.rb
Fix #311 
- When running `#add_attachment` with Faraday, wrap File with `Faraday::Multipart::FilePart`
=> Fix #add_attachment multipart upload with Faraday

.github/workflows/main.yml, Gemfile, README.md, lib/trello/action.rb, lib/trello/board.rb, lib/trello/card.rb, lib/trello/comment.rb, lib/trello/notification.rb, lib/trello/organization.rb, matrixeval.yml, spec/action_spec.rb, spec/association_spec.rb, spec/board_spec.rb, spec/card_spec.rb, spec/cassettes/can_get_boards_of_organization.yml, spec/cassettes/can_get_boards_with_filter_of_organization.yml, spec/integration/organization/associations/boards_spec.rb, spec/notification_spec.rb
- [Feature request for support query parameters](https://github.com/jeremytregunna/ruby-trello/issues/313)
- Support query parameter for most Model methods
=> Support query parameters for most model GET like methods
